### ISSUE TITLE
Earth hyperlink not displaying in red

### ISSUE THREAD

**Issue by allenk3** [allenk3/Elemental#1]
The 'earth' hyperlink on https://github.com/allenk3/Elemental/blob/master/list.html is displayed in blue, not red as per the spec

**Comment by charredprawns** [comment]
The "earth" hyperlink on list.html has had its color value changed to red as per the spec.

**Comment by allenk3** [comment]
Fixed in 07fd53746275890754c374a84c58c67d186e82b2
