### ISSUE TITLE
Broken hyperlink on list.html

### ISSUE THREAD

**Issue by allenk3** [allenk3/Elemental#2]
'Return to the Main Element Screen...' hyperlink at the bottom of https://github.com/allenk3/Elemental/blob/master/list.html links to indxe.html instead of index.html

**Comment by charredprawns** [comment]
'Return to the Main Element Screen...' hyperlink at the bottom the list.html has been changed from "indxe.html" to "index.html".

**Comment by allenk3** [comment]
Fixed in 07fd53746275890754c374a84c58c67d186e82b2
