### ISSUE TITLE
Broken hyperlink on air.html

### ISSUE THREAD

**Issue by allenk3** [allenk3/Elemental#3]
'Return to the Elements List...' hyperlink at the bottom of https://github.com/allenk3/Elemental/blob/master/air.html links to lits.html instead of list.html

**Comment by charredprawns** [comment]
The hyperlink for 'Return to the Elements List...'  has been changed from "lits.html" to "list.html"

**Comment by allenk3** [comment]
Fixed in 07fd53746275890754c374a84c58c67d186e82b2
